### ISSUE TITLE
Error 401 while using apps

### ISSUE THREAD

**Issue by jpripen** [chaimeleon-eu/CHAIMELEON-Platform#10]
When trying to use an app in one dataset (e.g., Maastricht Lung) the following error appears:

Unable to load Kubeapps configuration: Request failed with status code 401

I was able to perform that operation previously without errors.

**Comment by iblanque** [comment]
Strange, I have just done it, and it works. Can you check it again? We are suffering some unexpected delays with the proxy. If it works now it may be caused by it.  Please let us know.

**Comment by jpripen** [comment]
Now it works fine. Thanks, Nacho.
