### ISSUE TITLE
Python Kernel Upgrade and Package Installation Request

### ISSUE THREAD

**Issue by Nandayang** [chaimeleon-eu/CHAIMELEON-Platform#11]
I am writing to request assistance with an issue I've encountered while trying to use the platform and launch various applications. I've noticed that I'm unable to utilize some packages due to a lack of internet access for their installation.

The specific packages that I need include the following:
simpleitk, h5py, nibabel, scikit-image, tqdm, pandas,opencv-python-headless, argparse, scipy

While I appreciate that the current Python core has most of these packages installed, I specifically need the 'SimpleITK' package to handle volumetric images, as the 'pydicom' package does not adequately meet my requirements.

Could you kindly consider upgrading the Python kernel on the platform and adding these packages to the environment? Your assistance with this issue will greatly facilitate the progress of my work.

Regenerate response

**Comment by Palollo** [comment]
The packages have been added.
