### ISSUE TITLE
Functionality: Cancel and restart Dataset Creation Process

### ISSUE THREAD

**Issue by dsegrelles** [chaimeleon-eu/CHAIMELEON-Platform#16]
It would be desirable to have a functionality that would allow the process of creating a dataset to be cancelled, stopped and restarted. Currently, if the process is stopped or cancelled, it is restarted from the beginning, sometimes being processes that can last many hours.

**Comment by Palollo** [comment]
Cache for recently calculated hashes of series has been added:
https://github.com/chaimeleon-eu/dataset-service/commit/2c045604db70ed58d04d93ec184033600df2901d
