### ISSUE TITLE
Registration process

### ISSUE THREAD

**Issue by iblanque** [chaimeleon-eu/CHAIMELEON-Platform#2]
Hi,

It is unclear which should be the first step of a new user. The message "New user? -> register" will catch all the new users even if they already have credentials on an IdP. Would it be possible to clarify for a new user with credentials in a supported IdP that he should click on "Google / EGI Check-in"? 

Thanks!

**Comment by Palollo** [comment]
We can change the text to something like this:
```
New user? 
  - Use the previous links to sign in with your account of EGI Check-In or Google. 
  - Or use the previous links to create an account in EGI Check-In or Google.
  - Or you can <a>create an account</a> directly in CHAIMELEON platform.
```

**Comment by Palollo** [comment]
Too much text.
Finally a better solution:
![cap](https://user-images.githubusercontent.com/10077592/213727009-0e0d412e-a287-4668-b3ae-7bad2a2e551c.png)
