### ISSUE TITLE
Confirmation mail from KeyCloack should be under an official name

### ISSUE THREAD

**Issue by iblanque** [chaimeleon-eu/CHAIMELEON-Platform#4]
The source of the confirmation mail from KeyCloack is from Sergio, but an "official" mail should be used instead.

Something like "info@chaimeleon.eu" or at least "chaimeleon@upv.es"

Thanks

**Comment by Palollo** [comment]
This is an old issue.
The verification e-mail is currently sent from: security.chaimeleon-eu@i3m.upv.es
Also the e-mail for notification when the account is validated by the comittee and the required roles has been granted.
