### ISSUE TITLE
Deleted App is not removed from Desktop Apps Access

### ISSUE THREAD

**Issue by sophiasw** [chaimeleon-eu/CHAIMELEON-Platform#8]
The desktop access still lists an application after I deleted it. It is not listed in the Apps Dashboard and it can not be connected to, but it remains on the Desktop apps access. Also after logging out and back in.

**Comment by Palollo** [comment]
Thanks for reporting.
This is a known issue. Actually the user can manage the connections in the "Desktop Apps Access". In the beginning the user had to create the connection also, but later a script to automate this was included on the init of desktops.
Now there is a _kuberntes operator_ which will be used to create and also **delete** automatically the connections. It will be hopefully soon ;)

**Comment by Palollo** [comment]
Now the connections in the "Desktop Apps Access" are created and also deleted automatically.
